name: 'Test'

on:
  push:
    branches:
      - master
      - main
      - feature/*

  workflow_dispatch:
    inputs:
      name:
        description: 'The name which we should greet.'
        required: true
        default: 'World'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: Say hello
    steps:
      # To use a private repo action, the action repo must be checked out
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello World
        uses: ./  # Root directory action
        id: hello
        with:
          who-to-greet: ${{ github.event.inputs.name }}
      - name: Get Hello World time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

